import { Inter } from "next/font/google"

import { Toaster } from "~/components/ui/toaster"
import { cn } from "~/lib/utils"
import "~/styles/globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap"
})

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={cn("bg-zinc-50 text-zinc-900 antialiased", fontSans.variable)}>
      <body className="min-h-screen">
        {children}
        <Toaster />
      </body>
    </html>
  )
}
