import { Inter } from "next/font/google"

import { Toaster } from "~/components/ui/toaster"
import { cn } from "~/lib/utils"
import "~/styles/globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap"
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={cn(
        "bg-zinc-50 text-zinc-900 antialiased dark:bg-zinc-800 dark:text-zinc-50",
        fontSans.variable
      )}
    >
      <body className="min-h-screen">
        {children}
        <Toaster />
      </body>
    </html>
  )
}
